from django.conf.urls.defaults import *
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    
    (r'^$',                                         'music.views.music'),
    (r'^music/$',                                   'music.views.music'),
    (r'^home/$',                                    'music.views.music'),
    (r'^music_admin/$',                             'music.views.music_admin'),
    (r'^test/$',                                    'music.views.catalog_drive_music'),
    (r'^login/$',                                   'music_server.views.user_login' ),
    (r'^logout/$',                                  'music_server.views.user_logout' ),
    (r'^register/$',                                'music_server.views.register_user' ),
    (r'^is_admin/$',                                'music_server.views.is_admin' ),
    (r'^check_session/$',                           'music_server.views.check_session' ),
#    
    (r'^add_music/rebuild/$',                       'music.views.rebuild_music_db'),
    (r'^add_music/add/$',                           'music.views.add_to_music_db'),
    (r'^add_music/upload/$',                        'music.views.upload_music'),
      
    (r'^album_info/(?P<album_id>\d+)/$',            'music.views.album_info'),
    (r'^album_show/(?P<album_id>\d+)/$',            'music.views.album'),
    (r'^album_delete/(?P<album_id>\d+)/$',          'music.views.delete_album'),
    (r'^album_get_art/(?P<album_id>\d+)/$',         'music.views.get_single_album_art'),
    (r'^album_get_single_art/(?P<album_id>\d+)/$',  'music.views.get_single_album_art'),
    (r'^album_share/(?P<album_id>\d+)/$',           'music.views.share_album'),
    (r'^download_album/(?P<album_id>\d+)/$',        'music.views.download_album'),
    (r'^albums_by_artist/(?P<artist_id>\d+)/$',     'music.views.albums_by_artist'),
    (r'^albums_by_genre/(?P<genre_id>\d+)/$',       'music.views.albums_by_genre'),
    (r'^albums_by_year/(?P<year_id>\d+)/$',         'music.views.albums_by_year'),
    (r'^song/(?P<song_id>\d+)/$',                   'music.views.get_song'),
    
    (r'^rating/(?P<song_id>\d+)/(?P<rating>\d+)/$', 'music.views.set_rating'),
    (r'^get_profile_song_columns/$',                'music.views.get_profile_song_columns'),
    (r'^set_profile_song_columns/$',                'music.views.set_profile_song_columns'),
    (r'^set_theme/$',                               'music.views.set_theme'),
    (r'^save_playlist/$',                               'music.views.save_playlist'),
       
    (r'^rename_nzbs/$',                             'music.views.rename_nzbs' ),
    (r'^filter_nzbs/$',                             'music.views.filter_nzbs' ), 
    (r'^copy_favs/$',                               'music.views.copy_favs' ), 
    (r'^update_album_art/$',                        'music.views.update_album_art' ),  
    
    (r'^search_music_artists/$',                    'music.views.search_music_artists'),
    (r'^search_music_albums/$',                     'music.views.search_music_albums'),
    (r'^search_music_songs/$',                      'music.views.search_music_songs'),
    (r'^artists/0/$',                               'music.views.artists', {'letter': '0'}),
    (r'^artists/A/$',                               'music.views.artists', {'letter': 'A'}),
    (r'^artists/B/$',                               'music.views.artists', {'letter': 'B'}),
    (r'^artists/C/$',                               'music.views.artists', {'letter': 'C'}),
    (r'^artists/D/$',                               'music.views.artists', {'letter': 'D'}),
    (r'^artists/E/$',                               'music.views.artists', {'letter': 'E'}),
    (r'^artists/F/$',                               'music.views.artists', {'letter': 'F'}),
    (r'^artists/G/$',                               'music.views.artists', {'letter': 'G'}),
    (r'^artists/H/$',                               'music.views.artists', {'letter': 'H'}),
    (r'^artists/I/$',                               'music.views.artists', {'letter': 'I'}),
    (r'^artists/J/$',                               'music.views.artists', {'letter': 'J'}),
    (r'^artists/K/$',                               'music.views.artists', {'letter': 'K'}),
    (r'^artists/L/$',                               'music.views.artists', {'letter': 'L'}),
    (r'^artists/M/$',                               'music.views.artists', {'letter': 'M'}),
    (r'^artists/N/$',                               'music.views.artists', {'letter': 'N'}),
    (r'^artists/O/$',                               'music.views.artists', {'letter': 'O'}),
    (r'^artists/P/$',                               'music.views.artists', {'letter': 'P'}),
    (r'^artists/Q/$',                               'music.views.artists', {'letter': 'Q'}),
    (r'^artists/R/$',                               'music.views.artists', {'letter': 'R'}),
    (r'^artists/S/$',                               'music.views.artists', {'letter': 'S'}),
    (r'^artists/T/$',                               'music.views.artists', {'letter': 'T'}),
    (r'^artists/U/$',                               'music.views.artists', {'letter': 'U'}),
    (r'^artists/V/$',                               'music.views.artists', {'letter': 'V'}),
    (r'^artists/VA/$',                              'music.views.artists', {'letter': 'VA'}),
    (r'^artists/OST/$',                             'music.views.artists', {'letter': 'OST'}),
    (r'^artists/W/$',                               'music.views.artists', {'letter': 'W'}),
    (r'^artists/X/$',                               'music.views.artists', {'letter': 'X'}),
    (r'^artists/Y/$',                               'music.views.artists', {'letter': 'Y'}),
    (r'^artists/Z/$',                               'music.views.artists', {'letter': 'Z'}),
    (r'^artists/all/$',                             'music.views.artists', {'letter': 'all'}),
    
    (r'^albums/0/$',                           'music.views.albums', {'letter': '0'}),
    (r'^albums/A/$',                           'music.views.albums', {'letter': 'A'}),
    (r'^albums/B/$',                           'music.views.albums', {'letter': 'B'}),
    (r'^albums/C/$',                           'music.views.albums', {'letter': 'C'}),
    (r'^albums/D/$',                           'music.views.albums', {'letter': 'D'}),
    (r'^albums/E/$',                           'music.views.albums', {'letter': 'E'}),
    (r'^albums/F/$',                           'music.views.albums', {'letter': 'F'}),
    (r'^albums/G/$',                           'music.views.albums', {'letter': 'G'}),
    (r'^albums/H/$',                           'music.views.albums', {'letter': 'H'}),
    (r'^albums/I/$',                           'music.views.albums', {'letter': 'I'}),
    (r'^albums/J/$',                           'music.views.albums', {'letter': 'J'}),
    (r'^albums/K/$',                           'music.views.albums', {'letter': 'K'}),
    (r'^albums/L/$',                           'music.views.albums', {'letter': 'L'}),
    (r'^albums/M/$',                           'music.views.albums', {'letter': 'M'}),
    (r'^albums/N/$',                           'music.views.albums', {'letter': 'N'}),
    (r'^albums/O/$',                           'music.views.albums', {'letter': 'O'}),
    (r'^albums/P/$',                           'music.views.albums', {'letter': 'P'}),
    (r'^albums/Q/$',                           'music.views.albums', {'letter': 'Q'}),
    (r'^albums/R/$',                           'music.views.albums', {'letter': 'R'}),
    (r'^albums/S/$',                           'music.views.albums', {'letter': 'S'}),
    (r'^albums/T/$',                           'music.views.albums', {'letter': 'T'}),
    (r'^albums/U/$',                           'music.views.albums', {'letter': 'U'}),
    (r'^albums/V/$',                           'music.views.albums', {'letter': 'V'}),
    (r'^albums/W/$',                           'music.views.albums', {'letter': 'W'}),
    (r'^albums/X/$',                           'music.views.albums', {'letter': 'X'}),
    (r'^albums/Y/$',                           'music.views.albums', {'letter': 'Y'}),
    (r'^albums/Z/$',                           'music.views.albums', {'letter': 'Z'}),
    (r'^albums/all/$',                           'music.views.albums', {'letter': 'all'}),
    

    (r'^rebuild/0/$',                           'music.views.rebuild', {'letter': '0'}),
    (r'^rebuild/A/$',                           'music.views.rebuild', {'letter': 'A'}),
    (r'^rebuild/B/$',                           'music.views.rebuild', {'letter': 'B'}),
    (r'^rebuild/C/$',                           'music.views.rebuild', {'letter': 'C'}),
    (r'^rebuild/D/$',                           'music.views.rebuild', {'letter': 'D'}),
    (r'^rebuild/E/$',                           'music.views.rebuild', {'letter': 'E'}),
    (r'^rebuild/F/$',                           'music.views.rebuild', {'letter': 'F'}),
    (r'^rebuild/G/$',                           'music.views.rebuild', {'letter': 'G'}),
    (r'^rebuild/H/$',                           'music.views.rebuild', {'letter': 'H'}),
    (r'^rebuild/I/$',                           'music.views.rebuild', {'letter': 'I'}),
    (r'^rebuild/J/$',                           'music.views.rebuild', {'letter': 'J'}),
    (r'^rebuild/K/$',                           'music.views.rebuild', {'letter': 'K'}),
    (r'^rebuild/L/$',                           'music.views.rebuild', {'letter': 'L'}),
    (r'^rebuild/M/$',                           'music.views.rebuild', {'letter': 'M'}),
    (r'^rebuild/N/$',                           'music.views.rebuild', {'letter': 'N'}),
    (r'^rebuild/O/$',                           'music.views.rebuild', {'letter': 'O'}),
    (r'^rebuild/P/$',                           'music.views.rebuild', {'letter': 'P'}),
    (r'^rebuild/Q/$',                           'music.views.rebuild', {'letter': 'Q'}),
    (r'^rebuild/R/$',                           'music.views.rebuild', {'letter': 'R'}),
    (r'^rebuild/S/$',                           'music.views.rebuild', {'letter': 'S'}),
    (r'^rebuild/T/$',                           'music.views.rebuild', {'letter': 'T'}),
    (r'^rebuild/U/$',                           'music.views.rebuild', {'letter': 'U'}),
    (r'^rebuild/V/$',                           'music.views.rebuild', {'letter': 'V'}),
    (r'^rebuild/W/$',                           'music.views.rebuild', {'letter': 'W'}),
    (r'^rebuild/X/$',                           'music.views.rebuild', {'letter': 'X'}),
    (r'^rebuild/Y/$',                           'music.views.rebuild', {'letter': 'Y'}),
    (r'^rebuild/Z/$',                           'music.views.rebuild', {'letter': 'Z'}),
    (r'^rebuild/all/$',                         'music.views.rebuild', {'letter': 'all'}),    

)

if settings.DEBUG:
    urlpatterns += patterns( '',
        url( r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT} ),
        url( r'^/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.DRIVE} ),
    )
